set nocompatible
filetype off

call plug#begin('~/.vim/plugged')

" Basic
Plug 'sjl/vitality.vim'
Plug 'tpope/vim-sensible'

" Project
Plug 'dense-analysis/ale'

" Language
Plug 'sheerun/vim-polyglot'
Plug 'dag/vim-fish'

call plug#end()

" Leader
let mapleader=" "  " Map <leader> to space

" Rapid editing for vimrc
nmap <leader>rc :vsp $MYVIMRC<cr>
cmap <leader>so :source $MYVIMRC<cr>

" Pre-populate a split command with the current directory
nmap <leader>v :vnew <C-r>=escape(expand("%:p:h"), ' ') . '/'<cr>

" Map Commands
nmap 0 ^  " Easy access to the start of the line
nmap k gk " Move up by visible lines if current line is wrapped
nmap j gj " Move down by visible lines if current line is wrapped

" Interface
set number         " Show line numbers
set relativenumber " Line numbers relative to cursor
set showmode       " Show the mode in use
set cursorline     " Highlight current line
set wrap           " Turn on line wrapping
set colorcolumn=80 " Show a column at 80
set title          " Set the terminal title
set visualbell     " Disable beeping
set showcmd        " Show the (partial) command as it's being typed

" Status Bar
set laststatus=2 " Always show status bar
" Highlight the status bar when in insert mode
au InsertEnter * hi StatusLine ctermfg=235 ctermbg=10
au InsertLeave * hi StatusLine ctermfg=15 ctermbg=240

" Search
set hlsearch   " Highlight all search matches
set incsearch  " Highlight matches as you type
set ignorecase
set smartcase  " Be case-sensitive if expression contains a capital letter

" Backup
set nobackup
set nowritebackup
set directory=$HOME/.vim/tmp//,. " Keep swap files in one place

" Formatting
set tabstop=4    " Use 4 spaces to a tab
set shiftwidth=4 " As above
set expandtab    " Expand tabs into spaces
set showbreak=↪

" Disable arrow keys
no <down> <Nop>
no <left> <Nop>
no <right> <Nop>
no <up> <Nop>

" Copy copy register to OS X general pasteboard
function! PBCopy()
  call system("pbcopy", getreg(""))
endfunction

" Paste from OS X general pasteboard to copy register
function! PBPaste()
  call setreg("", system("pbpaste"))
endfunction

" By the power of https://github.com/sjl/vitality.vim, copies and pastes
" to the OS X pasteboard when switching between vim and other windows
" (even in tmux)
autocmd FocusLost * :call PBCopy()
autocmd FocusGained * :call PBPaste()

" Teach a Vim to fish...
" https://github.com/dag/vim-fish#teach-a-vim-to-fish
if &shell =~# 'fish$'
  set shell=bash
endif

