local function hex_to_rgb(hex)
  hex = hex:gsub("#", "")
  return tonumber(hex:sub(1, 2), 16), tonumber(hex:sub(3, 4), 16), tonumber(hex:sub(5, 6), 16)
end

local function rgb_to_hex(r, g, b)
  return string.format("#%02x%02x%02x", math.floor(r + 0.5), math.floor(g + 0.5), math.floor(b + 0.5))
end

local function mix(hex1, hex2, amount)
  local r1, g1, b1 = hex_to_rgb(hex1)
  local r2, g2, b2 = hex_to_rgb(hex2)
  local t = amount / 100
  return rgb_to_hex(r1 + (r2 - r1) * t, g1 + (g2 - g1) * t, b1 + (b2 - b1) * t)
end

local function lighten(hex, amount)
  return mix(hex, "#ffffff", amount)
end

local function darken(hex, amount)
  return mix(hex, "#000000", amount)
end

local M = {}

function M.setup(c)
  local hi = function(name, opts)
    vim.api.nvim_set_hl(0, name, opts)
  end

  -- Core UI
  hi("ColorColumn", {})
  hi("Conceal", {})
  hi("Cursor", { bg = c.cursor })
  hi("CurSearch", { bg = c.yellow, fg = c.bg })
  hi("CursorLine", { bg = c.bg })
  hi("Directory", { fg = c.blue })
  hi("DiffAdd", { fg = c.git_add })
  hi("DiffChange", { fg = c.git_change })
  hi("DiffDelete", { fg = c.git_delete })
  hi("DiffText", { bg = darken(c.git_delete, 30) })
  hi("ErrorMsg", { fg = c.fg })
  hi("VertSplit", { fg = c.unimportant })
  hi("Folded", { fg = mix(c.bg, c.fg, 40), bg = mix(c.bg, c.fg, 2) })
  hi("SignColumn", { bg = c.bg })
  hi("LineNr", { fg = mix(c.bg, c.fg, 22) })
  hi("LineNrAbove", { fg = mix(c.bg, c.fg, 22) })
  hi("LineNrBelow", { fg = mix(c.bg, c.fg, 22) })
  hi("CursorLineNr", { bg = mix(c.bg, c.fg, 10), fg = c.fg_base })
  hi("MatchParen", { fg = c.cursor })
  hi("MsgArea", { bg = c.bg_sidebar, fg = mix(c.fg_base, c.bg, 10) })
  hi("NonText", { fg = c.unimportant })
  hi("Normal", { bg = c.bg, fg = c.fg })
  hi("NormalFloat", { bg = c.bg_menu, fg = c.fg_menu })
  hi("Pmenu", { bg = c.bg_menu, fg = c.fg_menu })
  hi("PmenuSel", { bg = mix(c.bg_menu, c.fg, 10) })
  hi("PmenuSbar", { bg = c.bg_menu })
  hi("PmenuThumb", { bg = mix(c.bg_menu, c.fg, 10) })
  hi("Search", { bg = darken(c.orange, 80), bold = true })
  hi("StatusLine", { bg = c.bg_sidebar, fg = c.fg_sidebar })
  hi("StatusLineNC", { bg = c.bg_sidebar, fg = c.bg_sidebar })
  hi("Title", { fg = c.magenta })
  hi("Visual", { bg = c.selection })
  hi("WarningMsg", { fg = c.red })
  hi("Whitespace", { fg = mix(c.bg, c.fg, 2) })
  hi("Winseparator", { fg = mix(c.bg, c.fg, 5) })

  -- Syntax
  hi("Comment", { fg = c.unimportant })
  hi("String", { fg = c.green })
  hi("Character", { fg = c.green })
  hi("Number", { fg = c.green })
  hi("Boolean", { fg = c.green })
  hi("Float", { fg = c.green })
  hi("Identifier", { fg = c.fg_base })
  hi("Function", { fg = c.fg_base })
  hi("Conditional", { fg = c.blue })
  hi("Repeat", { fg = c.blue })
  hi("Label", { fg = c.blue })
  hi("Operator", { fg = c.orange })
  hi("Keyword", { fg = c.blue })
  hi("Exception", { fg = c.blue })
  hi("Include", { fg = c.blue })
  hi("Type", { fg = c.fg_base })
  hi("Special", { fg = c.unimportant })

  -- LSP
  hi("LspInlayHint", { bg = mix(c.bg, c.fg, 2), fg = c.unimportant })
  hi("DiagnosticError", { fg = c.red })
  hi("DiagnosticWarn", { fg = c.yellow })
  hi("DiagnosticSignHint", { fg = c.unimportant })
  hi("DiagnosticUnderlineError", { fg = c.red, undercurl = true })
  hi("DiagnosticUnderlineWarn", { fg = c.yellow, undercurl = true })

  -- Treesitter
  hi("@punctuation", { fg = c.unimportant })
  hi("@punctuation.special", { fg = c.blue })
  hi("@constant.builtin", { fg = c.orange })
  hi("@string", { fg = c.green })
  hi("@number", { fg = c.green })
  hi("@boolean", { fg = c.green })
  hi("@float", { fg = c.green })
  hi("@constructor", { fg = c.fg_base })
  hi("@conditional.ternary", { fg = c.orange })
  hi("@operator", { fg = c.orange })
  hi("@keyword", { fg = c.blue })
  hi("@keyword.operator", { fg = c.orange })
  hi("@type.builtin", { fg = c.orange })
  hi("@type.qualifier", { fg = c.blue })
  hi("@function.typescript", { fg = c.fg_base, bold = true })
  hi("@lsp.typemod.type.declaration.typescript", { fg = c.orange })
  hi("@lsp.typemod.variable.defaultLibrary", { fg = lighten(c.orange, 25) })
  hi("@variable.rust", { fg = c.blue })
  hi("@lsp.typemod.generic.macro.rust", { fg = c.green })
  hi("@spell.markdown", { fg = c.fg_base })
  hi("@markup.heading", { fg = c.fg, bold = true })
  hi("@markup.heading.1.marker.markdown", { fg = c.unimportant })
  hi("@markup.heading.2.marker.markdown", { fg = c.unimportant })
  hi("@markup.heading.3.marker.markdown", { fg = c.unimportant })
  hi("@markup.heading.4.marker.markdown", { fg = c.unimportant })
  hi("@markup.heading.5.marker.markdown", { fg = c.unimportant })
  hi("@markup.heading.6.marker.markdown", { fg = c.unimportant })
  hi("@markup.list.markdown", { fg = c.unimportant })
  hi("@markup.raw.markdown_inline", { fg = c.unimportant })
  hi("@markup.link.markdown_inline", { fg = c.unimportant })
  hi("@conceal.markdown", { fg = c.unimportant })

  -- Nix
  hi("nixListBracket", { fg = c.unimportant })
  hi("nixInterpolation", { fg = c.orange })
  hi("nixInterpolationParam", { fg = c.orange })
  hi("nixFunctionCall", { fg = c.blue })
  hi("nixAttributeAssignment", { fg = c.orange })

  -- lazy.nvim
  hi("LazyNormal", { bg = c.bg_sidebar, fg = c.fg_sidebar })
  hi("LazyH1", { fg = c.magenta })

  -- nvim-notify
  hi("NotifyDEBUGBody", {})
  hi("NotifyDEBUGBorder", {})
  hi("NotifyDEBUGIcon", {})
  hi("NotifyDEBUGTitle", {})
  hi("NotifyERRORBody", {})
  hi("NotifyERRORBorder", { fg = darken(c.red, 50) })
  hi("NotifyERRORIcon", { fg = c.red })
  hi("NotifyERRORTitle", { fg = c.red })
  hi("NotifyINFOBody", {})
  hi("NotifyINFOBorder", { fg = darken(c.blue, 50) })
  hi("NotifyINFOIcon", { fg = c.blue })
  hi("NotifyINFOTitle", { fg = c.blue })
  hi("NotifyTRACEBody", {})
  hi("NotifyTRACEBorder", { fg = darken(c.magenta, 50) })
  hi("NotifyTRACEIcon", { fg = c.magenta })
  hi("NotifyTRACETitle", { fg = c.magenta })
  hi("NotifyWARNBody", {})
  hi("NotifyWARNBorder", { fg = darken(c.yellow, 50) })
  hi("NotifyWARNIcon", { fg = c.yellow })
  hi("NotifyWARNTitle", { fg = c.yellow })

  -- neotest
  hi("NeotestAdapterName", { fg = c.unimportant })
  hi("NeotestDir", { fg = c.unimportant })
  hi("NeotestFailed", { fg = c.red })
  hi("NeotestFile", { fg = c.fg })
  hi("NeotestIndent", { fg = mix(c.bg, c.fg, 10) })
  hi("NeotestExpandMarker", { fg = mix(c.bg, c.fg, 10) })
  hi("NeotestPassed", { fg = c.green })
  hi("NeotestRunning", { fg = c.yellow })
  hi("NeotestSkipped", { fg = c.blue })
  hi("NeotestNamespace", {})
  hi("NeotestFocused", { bg = mix(c.bg, c.fg, 5) })
  hi("NeotestWinSelect", {})
  hi("NeotestMarked", {})
  hi("NeotestTarget", {})
  hi("NeotestWatching", {})
  hi("NeotestUnknown", { fg = c.unimportant })

  -- neo-tree
  hi("NeoTreeCursorLine", { bg = mix(c.bg_sidebar, c.fg, 8) })
  hi("NeoTreeDirectoryName", { fg = c.fg_sidebar })
  hi("NeoTreeDirectoryIcon", { fg = mix(c.bg_sidebar, c.fg, 20) })
  hi("NeoTreeDotfile", { fg = c.fg_sidebar })
  hi("NeoTreeGitAdded", { fg = c.fg_sidebar })
  hi("NeoTreeGitConflict", { fg = c.fg_sidebar })
  hi("NeoTreeGitDeleted", { fg = c.fg_sidebar })
  hi("NeoTreeGitIgnored", { fg = mix(c.bg, c.fg, 15) })
  hi("NeoTreeGitModified", { fg = c.fg_sidebar })
  hi("NeoTreeGitUnstaged", { fg = c.fg_sidebar })
  hi("NeoTreeGitUntracked", { fg = c.fg_sidebar })
  hi("NeoTreeHiddenByName", { fg = c.unimportant })
  hi("NeoTreeIndentMarker", { fg = mix(c.bg_sidebar, c.fg, 8) })
  hi("NeoTreeModified", { fg = c.unimportant })
  hi("NeoTreeNormal", { bg = c.bg_sidebar, fg = c.fg_sidebar })
  hi("NeoTreeNormalNc", { bg = c.bg_sidebar, fg = c.fg_sidebar })
  hi("NeoTreeRootName", { fg = c.fg_sidebar })
  hi("NeoTreeWinSeparator", { bg = c.bg_sidebar, fg = c.bg_sidebar })

  -- Noice
  hi("NoiceCmdlineIcon", { fg = c.green })
  hi("NoiceCmdlineIconSearch", { fg = c.yellow })
  hi("NoiceCmdlinePopup", { bg = c.bg_sidebar })
  hi("NoiceCmdlinePopupBorder", { fg = c.unimportant })
  hi("NoiceCmdlinePopupTitle", { fg = c.unimportant })
  hi("NoicePopupmenu", { bg = c.bg_sidebar })
  hi("NoicePopupmenuBorder", { fg = c.unimportant })
  hi("NoiceCompletionItemMenu", { bg = c.bg_sidebar })

  -- vim-illuminate
  hi("IlluminatedWordText", { bg = mix(c.bg, c.fg, 5) })
  hi("IlluminatedWordRead", { bg = mix(c.bg, c.fg, 5) })

  -- twoslash-queries.nvim
  hi("TypeVirtualText", { bg = mix(c.bg, c.fg, 3), fg = mix(c.fg_base, c.bg, 5) })

  -- mini.nvim
  hi("MiniIconsAzure", { fg = c.fg_sidebar })
  hi("MiniIconsBlue", { fg = c.fg_sidebar })
  hi("MiniIconsCyan", { fg = c.fg_sidebar })
  hi("MiniIconsGreen", { fg = c.fg_sidebar })
  hi("MiniIconsGrey", { fg = c.fg_sidebar })
  hi("MiniIconsOrange", { fg = c.fg_sidebar })
  hi("MiniIconsPurple", { fg = c.fg_sidebar })
  hi("MiniIconsRed", { fg = c.fg_sidebar })
  hi("MiniIconsYellow", { fg = c.fg_sidebar })

  -- gitsigns
  hi("GitSignsAdd", { fg = c.git_add })
  hi("GitSignsChange", { fg = c.git_change })
  hi("GitSignsDelete", { fg = c.git_delete })

  -- copilot-cmp
  hi("CmpItemKindCopilot", { fg = c.unimportant })

  -- nvim-scrollbar
  hi("ScrollbarHandle", { bg = c.bg_menu, fg = c.fg_base })
  hi("ScrollbarCursor", { fg = c.fg_base })
  hi("ScrollbarCursorHandle", { bg = c.bg_menu, fg = c.fg_base })
  hi("ScrollbarError", { fg = c.red })
  hi("ScrollbarErrorHandle", { bg = c.bg_menu, fg = c.red })
  hi("ScrollbarGitAdd", { fg = c.git_add })
  hi("ScrollbarGitAddHandle", { bg = c.bg_menu, fg = c.git_add })
  hi("ScrollbarGitChange", { fg = c.git_change })
  hi("ScrollbarGitChangeHandle", { bg = c.bg_menu, fg = c.git_change })
  hi("ScrollbarGitDelete", { fg = c.git_delete })
  hi("ScrollbarGitDeleteHandle", { bg = c.bg_menu, fg = c.git_delete })
  hi("ScrollbarHint", { fg = c.unimportant })
  hi("ScrollbarHintHandle", { bg = c.bg_menu, fg = c.unimportant })
  hi("ScrollbarInfo", { fg = c.blue })
  hi("ScrollbarInfoHandle", { bg = c.bg_menu, fg = c.blue })
  hi("ScrollbarMisc", { fg = c.magenta })
  hi("ScrollbarMiscHandle", { bg = c.bg_menu, fg = c.magenta })
  hi("ScrollbarSearch", { fg = c.orange })
  hi("ScrollbarSearchHandle", { bg = c.bg_menu, fg = c.orange })
  hi("ScrollbarWarn", { fg = c.yellow })
  hi("ScrollbarWarnHandle", { bg = c.bg_menu, fg = c.yellow })

  -- which-key
  hi("WhichKeyDesc", { fg = c.fg_sidebar })
  hi("WhichKeyNormal", { bg = c.bg_sidebar, fg = c.fg_sidebar })
  hi("WhichKeyBorder", { bg = c.bg_sidebar, fg = c.unimportant })
  hi("WhichKeyTitle", { bg = c.bg_sidebar, fg = c.magenta })

  -- lualine
  hi("StatusLineError", { bg = c.bg_sidebar, fg = c.red })
  hi("StatusLineWarn", { bg = c.bg_sidebar, fg = c.yellow })

  -- trouble.nvim
  hi("TroubleNormal", { bg = c.bg, fg = c.fg })
  hi("TroubleNormalNC", { bg = c.bg, fg = c.fg })
  hi("TroubleFsCount", { fg = c.unimportant })
  hi("TroubleDiagnosticsCount", { fg = c.unimportant })

  -- nvim-dap
  hi("DapStoppedLine", { bg = mix(c.bg, c.fg, 8) })

  -- nvim-dap-ui
  hi("DapUINormal", { fg = c.fg })
  hi("DapUIVariable", { fg = c.fg })
  hi("DapUIScope", { fg = c.blue })
  hi("DapUIType", { fg = c.magenta })
  hi("DapUIValue", { fg = c.fg })
  hi("DapUIModifiedValue", { fg = c.blue, bold = true })
  hi("DapUIDecoration", { fg = c.blue })
  hi("DapUIThread", { fg = c.green })
  hi("DapUIStoppedThread", { fg = c.blue })
  hi("DapUIFrameName", { fg = c.fg })
  hi("DapUISource", { fg = c.magenta })
  hi("DapUILineNumber", { fg = c.blue })
  hi("DapUIFloatNormal", { fg = c.fg })
  hi("DapUIFloatBorder", { fg = c.blue })
  hi("DapUIWatchesEmpty", { fg = c.red })
  hi("DapUIWatchesValue", { fg = c.green })
  hi("DapUIWatchesError", { fg = c.red })
  hi("DapUIBreakpointsPath", { fg = c.blue })
  hi("DapUIBreakpointsInfo", { fg = c.green })
  hi("DapUIBreakpointsCurrentLine", { fg = c.green })
  hi("DapUIBreakpointsLine", { fg = c.fg })
  hi("DapUIBreakpointsDisabledLine", { fg = c.unimportant })
  hi("DapUICurrentFrameName", { fg = c.fg })
  hi("DapUIStepOver", { fg = c.blue })
  hi("DapUIStepInto", { fg = c.blue })
  hi("DapUIStepBack", { fg = c.blue })
  hi("DapUIStepOut", { fg = c.blue })
  hi("DapUIStop", { fg = c.red })
  hi("DapUIPlayPause", { fg = c.green })
  hi("DapUIRestart", { fg = c.green })
  hi("DapUIUnavailable", { fg = c.unimportant })
  hi("DapUIWinSelect", { fg = c.blue })
  hi("DapUIEndofBuffer", { fg = c.fg })

  -- nvim-treesitter-context
  hi("TreesitterContext", { bg = c.bg_menu })

  -- snacks.nvim
  hi("SnacksIndent", { fg = mix(c.bg, c.fg, 4) })
  hi("SnacksIndentScope", { fg = mix(c.bg, c.fg, 16) })
  hi("SnacksNormal", { bg = c.bg, fg = c.fg })
  hi("SnacksNormalNC", { bg = c.bg, fg = c.fg })
  hi("SnacksNotifierBorderInfo", { fg = c.blue })
  hi("SnacksNotifierTitleInfo", { fg = c.blue })
  hi("SnacksPickerBorder", { bg = c.bg_sidebar, fg = c.unimportant })
  hi("SnacksPickerDir", { fg = c.unimportant })
  hi("SnacksPickerInput", { bg = c.bg_sidebar, fg = c.fg_sidebar })
  hi("SnacksPickerList", { bg = c.bg_sidebar, fg = c.fg_sidebar })
  hi("SnacksPickerListCursorLine", { bg = mix(c.bg_sidebar, c.fg, 10) })
  hi("SnacksPickerMatch", { fg = c.cursor })
  hi("SnacksPickerPickWin", { bg = c.bg_sidebar, fg = c.fg_sidebar })
  hi("SnacksPickerPreview", { bg = c.bg, fg = c.fg })
  hi("SnacksPickerPrompt", { fg = c.orange })
  hi("SnacksPickerTitle", { bg = c.bg_sidebar, fg = c.fg_sidebar })

  -- blink.cmp
  hi("BlinkCmpMenu", { bg = c.bg_menu, fg = c.fg_menu })

  -- grug-far.nvim
  hi("GrugFarHelpHeader", { fg = c.blue })
  hi("GrugFarHelpWinActionDescription", { fg = c.fg_sidebar })
  hi("GrugFarHelpWinActionPrefix", { fg = c.fg_sidebar })
  hi("GrugFarHelpWinActionText", { fg = c.blue })
  hi("GrugFarHelpWinHeader", { fg = c.cursor })
  hi("GrugFarInputLabel", { fg = c.blue })
  hi("GrugFarInputPlaceholder", { bg = c.bg, fg = c.fg_sidebar })
  hi("GrugFarNormal", { bg = c.bg_sidebar })
  hi("GrugFarResultsActionMessage", { fg = c.blue })
  hi("GrugFarResultsAddIndicator", { fg = c.git_add })
  hi("GrugFarResultsChangeIndicator", { fg = c.git_change })
  hi("GrugFarResultsHeader", { fg = c.fg_sidebar })
  hi("GrugFarResultsMatch", { fg = c.cursor })
  hi("GrugFarResultsMatchAdded", { fg = c.git_add })
  hi("GrugFarResultsMatchRemoved", { fg = c.git_delete })
  hi("GrugFarResultsNumberLabel", { fg = c.unimportant })
  hi("GrugFarResultsPath", { fg = c.fg_sidebar, underline = true })
  hi("GrugFarResultsRemoveIndicator", { fg = c.git_delete })

  -- oil.nvim
  hi("OilDirHidden", { fg = c.unimportant })
  hi("OilGitAdded", { fg = c.git_add })
  hi("OilGitModified", { fg = c.blue })
  hi("OilGitRenamed", { fg = c.magenta })
  hi("OilGitDeleted", { fg = c.git_delete })
  hi("OilGitCopied", { fg = c.magenta })
  hi("OilGitConflict", { fg = c.orange })
  hi("OilGitUntracked", { fg = c.green })
  hi("OilGitIgnored", { fg = c.unimportant })
end

return M
