{ config, ... }:
let
  ampProtectedCommands = [
    "*&&*"
    "*;*"
    "*$(*"
    "*>*"
    "*`*"
    "*|*"
    "*git*commit*"
    "*git*push*"
    "*git*rebase*"
    "*git*reset*"
    "*git*checkout*"
    "*git*switch*"
    "*git*clean*"
    "*rm *"
    "*find *-delete*"
    "*find *-exec*"
    "*find *-execdir*"
    "*install *"
    "*ln -sf*"
    "*chmod *"
    "*chown *"
    "*sudo *"
    "*tee *"
    "*sed -i*"
  ];
  ampSafeCommands = [
    "pwd"
    "pwd -P"
    "ls"
    "ls *"
    "eza"
    "eza *"
    "fd"
    "fd *"
    "rg"
    "rg *"
    "*/rg"
    "*/rg *"
    "* rg"
    "* rg *"
    "cat"
    "cat *"
    "head"
    "head *"
    "tail"
    "tail *"
    "nl"
    "nl *"
    "wc"
    "wc *"
    "file"
    "file *"
    "stat"
    "stat *"
    "sed -n *"
    "git status*"
    "git diff*"
    "git show*"
    "git log*"
    "git rev-parse*"
    "git ls-files*"
    "git grep*"
    "git blame*"
    "git branch"
    "git branch --show-current"
    "git branch --list*"
    "git remote -v"
    "git remote show*"
    "gh auth status*"
    "gh pr view*"
    "gh pr list*"
    "gh pr status*"
    "gh pr checks*"
    "gh pr diff*"
    "gh issue view*"
    "gh issue list*"
    "gh issue status*"
    "gh repo view*"
    "gh run view*"
    "gh run list*"
    "gh workflow view*"
    "gh workflow list*"
    "gh search *"
    "nix build*"
    "nix eval*"
    "nix flake show*"
    "nix flake metadata*"
    "nix flake check*"
    "darwin-rebuild build*"
    "sh -n *"
    "bash -n *"
    "fish -n *"
  ];
in
{
  xdg.configFile."amp/settings.json".text = builtins.toJSON {
    "//" = "Generated by ${config.home.sessionVariables.DOTFILES_HOME}/nix/modules/amp.nix";
    "amp.git.commit.coauthor.enabled" = false;
    "amp.git.commit.ampThread.enabled" = false;
    "amp.mcpServers" = {
      cloudflare-api = {
        url = "https://mcp.cloudflare.com/mcp";
      };
    };
    "amp.permissions" = [
      {
        tool = "mcp__cloudflare_api__execute";
        action = "ask";
      }
      # Add explicit overrides for risky commands and a small read-only
      # allowlist (notably rg), then let Amp's built-in defaults handle the rest.
      {
        tool = "Bash";
        matches.cmd = ampProtectedCommands;
        action = "ask";
      }
      {
        tool = "Bash";
        matches.cmd = ampSafeCommands;
        action = "allow";
      }
      {
        tool = "shell_command";
        matches.command = ampProtectedCommands;
        action = "ask";
      }
      {
        tool = "shell_command";
        matches.command = ampSafeCommands;
        action = "allow";
      }
    ];
    "amp.defaultVisibility" = {
      "github.com/tmm/dotfiles" = "private";
      "github.com/wevm/curl.md" = "private";
    };
    "amp.showCosts" = true;
  };
}
