{ config, ... }:
let
  ampProtectedCommands = [
    "sudo"
    "sudo *"
    "rm *"
    "rm -*"
    "find *-delete*"
    "git clean"
    "git clean *"
    "git clean -*"
    "git reset --hard"
    "git reset --hard *"
    "git reset * --hard"
    "git reset * --hard *"
    "git push"
    "git push *"
    "dd *of=/dev/*"
    "diskutil erase*"
    "mkfs*"
    "newfs*"
  ];
in
{
  xdg.configFile."amp/settings.json".text = builtins.toJSON {
    "//" = "Generated by ${config.home.sessionVariables.DOTFILES_HOME}/nix/modules/amp.nix";
    "amp.git.commit.coauthor.enabled" = false;
    "amp.git.commit.ampThread.enabled" = false;
    "amp.permissions" = [
      # Keep normal development flows unprompted and only interrupt for
      # commands that can permanently delete data, change remote state, or
      # escalate privileges.
      {
        tool = "Bash";
        matches.cmd = ampProtectedCommands;
        action = "ask";
      }
      {
        tool = "Bash";
        matches.cmd = "*";
        action = "allow";
      }
      {
        tool = "shell_command";
        matches.command = ampProtectedCommands;
        action = "ask";
      }
      {
        tool = "shell_command";
        matches.command = "*";
        action = "allow";
      }
    ];
    "amp.defaultVisibility" = {
      "github.com/tmm/dotfiles" = "private";
      "github.com/wevm/curl.md" = "private";
    };
    "amp.showCosts" = true;
  };
}
