{ config, ... }:
let
  ampProtectedCommands = [
    # Match shell operator tokens rather than any literal character in the
    # command string, so quoted regexes like `rg "foo|bar"` stay read-only.
    "/&&(?=\\s|$)/"
    "/;(?:\\s|$)/"
    "*$(*"
    "/>>(?:\\s|$)/"
    "/>(?=\\s|$)/"
    "/<<(?:\\s|$)/"
    "/<(?=\\s|$)/"
    "*`*"
    "/\\|(?=\\s|$)/"
    "*git*commit*"
    "*git*push*"
    "*git*rebase*"
    "*git*reset*"
    "*git*checkout*"
    "*git*switch*"
    "*git*clean*"
    "*rm *"
    "*find *-delete*"
    "*find *-exec*"
    "*find *-execdir*"
    "*install *"
    "*ln -sf*"
    "*chmod *"
    "*chown *"
    "*sudo *"
    "*tee *"
    "*sed -i*"
  ];
in
{
  xdg.configFile."amp/settings.json".text = builtins.toJSON {
    "//" = "Generated by ${config.home.sessionVariables.DOTFILES_HOME}/nix/modules/amp.nix";
    "amp.git.commit.coauthor.enabled" = false;
    "amp.git.commit.ampThread.enabled" = false;
    "amp.mcpServers" = {
      cloudflare-api = {
        url = "https://mcp.cloudflare.com/mcp";
      };
    };
    "amp.permissions" = [
      {
        tool = "mcp__cloudflare_api__execute";
        action = "ask";
      }
      # Ask before risky shell commands, but otherwise allow shell usage by
      # default instead of falling back to Amp's conservative built-in rules.
      {
        tool = "Bash";
        matches.cmd = ampProtectedCommands;
        action = "ask";
      }
      {
        tool = "Bash";
        matches.cmd = "*";
        action = "allow";
      }
      {
        tool = "shell_command";
        matches.command = ampProtectedCommands;
        action = "ask";
      }
      {
        tool = "shell_command";
        matches.command = "*";
        action = "allow";
      }
    ];
    "amp.defaultVisibility" = {
      "github.com/tmm/dotfiles" = "private";
      "github.com/wevm/curl.md" = "private";
    };
    "amp.showCosts" = true;
  };
}
